name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        echo "docker image build -t siggoglin/heatmaster:latest .
        ${{ secrets.DOCKERPW }}" | docker login -u "sigogglin" --password-stdin
        docker push sigogglin/heatmaster:latest
