name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:       run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "sigogglin" --password-stdin
        docker image build -t dpeart/heatmaster:latest .
        docker push dpeart/heatmaster:latest
